server:
  port: 8762

spring:
  application:
    name: service-hi
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh