server:
  port: 8761

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
  profiles: peer2